// <auto-generated />
using System;
using Domain.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20251102080718_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.District", b =>
                {
                    b.Property<string>("DistrictId")
                        .HasColumnType("text");

                    b.Property<string>("DistrictName")
                        .HasColumnType("text");

                    b.Property<string>("DistrictNameBN")
                        .HasColumnType("text");

                    b.Property<string>("DivisionId")
                        .HasColumnType("text");

                    b.HasKey("DistrictId");

                    b.ToTable("District");
                });

            modelBuilder.Entity("Domain.Aggregates.Division", b =>
                {
                    b.Property<string>("DivisionId")
                        .HasColumnType("text");

                    b.Property<string>("DivisionName")
                        .HasColumnType("text");

                    b.Property<string>("DivisionNameBN")
                        .HasColumnType("text");

                    b.HasKey("DivisionId");

                    b.ToTable("Division");
                });

            modelBuilder.Entity("Domain.Aggregates.Unions", b =>
                {
                    b.Property<string>("UnionId")
                        .HasColumnType("text");

                    b.Property<string>("DistrictId")
                        .HasColumnType("text");

                    b.Property<string>("DivisionId")
                        .HasColumnType("text");

                    b.Property<string>("UnionName")
                        .HasColumnType("text");

                    b.Property<string>("UnionNameBN")
                        .HasColumnType("text");

                    b.Property<string>("UpazilaId")
                        .HasColumnType("text");

                    b.HasKey("UnionId");

                    b.ToTable("Unions");
                });

            modelBuilder.Entity("Domain.Aggregates.Upazila", b =>
                {
                    b.Property<string>("UpazilaId")
                        .HasColumnType("text");

                    b.Property<string>("DistrictId")
                        .HasColumnType("text");

                    b.Property<string>("DivisionId")
                        .HasColumnType("text");

                    b.Property<string>("UpazilaName")
                        .HasColumnType("text");

                    b.Property<string>("UpazilaNameBN")
                        .HasColumnType("text");

                    b.HasKey("UpazilaId");

                    b.ToTable("Upazila");
                });

            modelBuilder.Entity("Domain.Aggregates.UserGeo", b =>
                {
                    b.Property<string>("UserGeoId")
                        .HasColumnType("text");

                    b.Property<string>("DistrictId")
                        .HasColumnType("text");

                    b.Property<string>("DivisionId")
                        .HasColumnType("text");

                    b.Property<string>("UnionId")
                        .HasColumnType("text");

                    b.Property<string>("UpazilaId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("VillageId")
                        .HasColumnType("text");

                    b.HasKey("UserGeoId");

                    b.ToTable("UserGeo");
                });

            modelBuilder.Entity("Domain.Aggregates.Village", b =>
                {
                    b.Property<string>("VillageId")
                        .HasColumnType("text");

                    b.Property<string>("DistrictId")
                        .HasColumnType("text");

                    b.Property<string>("DivisionId")
                        .HasColumnType("text");

                    b.Property<string>("UnionId")
                        .HasColumnType("text");

                    b.Property<string>("UpazilaId")
                        .HasColumnType("text");

                    b.Property<string>("VillageName")
                        .HasColumnType("text");

                    b.Property<string>("VillageNameBN")
                        .HasColumnType("text");

                    b.HasKey("VillageId");

                    b.ToTable("Village");
                });

            modelBuilder.Entity("RapidFireLib.Models.AppPermission", b =>
                {
                    b.Property<int>("AppPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppPermissionId"));

                    b.Property<int>("AppResourceId")
                        .HasColumnType("integer");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<bool>("vCreate")
                        .HasColumnType("boolean");

                    b.Property<bool>("vDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("vRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("vUpdate")
                        .HasColumnType("boolean");

                    b.HasKey("AppPermissionId");

                    b.ToTable("AppPermissions");
                });

            modelBuilder.Entity("RapidFireLib.Models.Approval", b =>
                {
                    b.Property<long>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ApprovalId"));

                    b.Property<string>("ApprovalItemId")
                        .HasColumnType("text");

                    b.Property<int?>("ApprovalStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("ApprovalUserType")
                        .HasColumnType("integer");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RequestOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("RequestedBy")
                        .HasColumnType("integer");

                    b.Property<string>("TableName")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("ApprovalId");

                    b.ToTable("Approval");
                });

            modelBuilder.Entity("RapidFireLib.Models.AuditTrail", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditId"));

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<string>("OperationType")
                        .HasColumnType("text");

                    b.Property<string>("RecordId")
                        .HasColumnType("text");

                    b.Property<string>("RefData")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("AuditId");

                    b.ToTable("AuditTrail");
                });

            modelBuilder.Entity("RapidFireLib.Models.AuditTrailView", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditId"));

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<string>("OperationType")
                        .HasColumnType("text");

                    b.Property<string>("RecordId")
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("AuditId");

                    b.ToTable("AuditTrailView");
                });

            modelBuilder.Entity("RapidFireLib.Models.ChatGroup", b =>
                {
                    b.Property<string>("ChatGroupId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomFlag")
                        .HasColumnType("text");

                    b.Property<string>("GroupType")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ChatGroupId");

                    b.ToTable("ChatGroup");
                });

            modelBuilder.Entity("RapidFireLib.Models.ChatGroupMember", b =>
                {
                    b.Property<string>("ChatGroupMemberId")
                        .HasColumnType("text");

                    b.Property<string>("ChatGroupId")
                        .HasColumnType("text");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("UserTable")
                        .HasColumnType("text");

                    b.HasKey("ChatGroupMemberId");

                    b.HasIndex("ChatGroupId");

                    b.ToTable("ChatGroupMember");
                });

            modelBuilder.Entity("RapidFireLib.Models.ChatMessage", b =>
                {
                    b.Property<string>("ChatMessageId")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime>("SendAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SendTo")
                        .HasColumnType("text");

                    b.Property<string>("Sender")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("ChatMessageId");

                    b.ToTable("ChatMessage");
                });

            modelBuilder.Entity("RapidFireLib.Models.ChatSeenUser", b =>
                {
                    b.Property<string>("ChatSeenUserId")
                        .HasColumnType("text");

                    b.Property<string>("ChatMessageId")
                        .HasColumnType("text");

                    b.Property<DateTime>("SeenAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("ChatSeenUserId");

                    b.HasIndex("ChatMessageId");

                    b.ToTable("ChatSeenUser");
                });

            modelBuilder.Entity("RapidFireLib.Models.DataVerificationLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("ChildTables")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClientUpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int?>("IsClientUpdated")
                        .HasColumnType("integer");

                    b.Property<int>("IsNotified")
                        .HasColumnType("integer");

                    b.Property<int>("NotifiedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("NotifiedTo")
                        .HasColumnType("integer");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryKey")
                        .HasColumnType("text");

                    b.Property<int?>("RecordType")
                        .HasColumnType("integer");

                    b.Property<string>("TableName")
                        .HasColumnType("text");

                    b.Property<string>("UUID")
                        .HasColumnType("text");

                    b.HasKey("LogId");

                    b.ToTable("DataVerificationLog");
                });

            modelBuilder.Entity("RapidFireLib.Models.FCMCUDSetup", b =>
                {
                    b.Property<string>("FCMCUDSetupId")
                        .HasColumnType("text");

                    b.Property<string>("CreateMessageBody")
                        .HasColumnType("text");

                    b.Property<string>("CreateMessageTitle")
                        .HasColumnType("text");

                    b.Property<string>("DeleteMessageBody")
                        .HasColumnType("text");

                    b.Property<string>("DeleteMessageTitle")
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<string>("UpdateMessageBody")
                        .HasColumnType("text");

                    b.Property<string>("UpdateMessageTitle")
                        .HasColumnType("text");

                    b.HasKey("FCMCUDSetupId");

                    b.ToTable("FCMCUDSetup");
                });

            modelBuilder.Entity("RapidFireLib.Models.FCMCUDTopic", b =>
                {
                    b.Property<string>("FCMCUDTopicId")
                        .HasColumnType("text");

                    b.Property<bool>("C")
                        .HasColumnType("boolean");

                    b.Property<bool>("D")
                        .HasColumnType("boolean");

                    b.Property<string>("FCMCUDSetupId")
                        .HasColumnType("text");

                    b.Property<string>("RoleTopic")
                        .HasColumnType("text");

                    b.Property<bool>("U")
                        .HasColumnType("boolean");

                    b.HasKey("FCMCUDTopicId");

                    b.HasIndex("FCMCUDSetupId");

                    b.ToTable("FCMCUDTopic");
                });

            modelBuilder.Entity("RapidFireLib.Models.FCMToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("Device")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("UserTable")
                        .HasColumnType("text");

                    b.HasKey("Token");

                    b.ToTable("FCMToken");
                });

            modelBuilder.Entity("RapidFireLib.Models.Identity.ApplicationUserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("RapidFireLib.Models.Messaging.EmailLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("CC")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("From")
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<string>("RecordId")
                        .HasColumnType("text");

                    b.Property<int?>("SentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<string>("To")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmailLog");
                });

            modelBuilder.Entity("RapidFireLib.Models.Messaging.Push.NotificationRule", b =>
                {
                    b.Property<int>("NotificationRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationRuleId"));

                    b.Property<string>("BodyTemplate")
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<string>("GeoFilterBy")
                        .HasColumnType("text");

                    b.Property<bool>("InAppPopup")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NotifyToAll")
                        .HasColumnType("boolean");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientRoles")
                        .HasColumnType("text");

                    b.Property<string>("RecipientUserFields")
                        .HasColumnType("text");

                    b.Property<string>("TitleTemplate")
                        .HasColumnType("text");

                    b.Property<string>("ToUrl")
                        .HasColumnType("text");

                    b.HasKey("NotificationRuleId");

                    b.ToTable("NotificationRule");
                });

            modelBuilder.Entity("RapidFireLib.Models.Messaging.Push.PushNotification", b =>
                {
                    b.Property<string>("PushNotificationId")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SendAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SendTo")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("ToUrl")
                        .HasColumnType("text");

                    b.HasKey("PushNotificationId");

                    b.ToTable("PushNotification");
                });

            modelBuilder.Entity("RapidFireLib.Models.Messaging.Push.PushNotificationSeen", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId");

                    b.ToTable("PushNotificationSeen");
                });

            modelBuilder.Entity("RapidFireLib.Models.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NotificationId"));

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<int?>("NotificationUserType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NotificationViewOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("NotifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NotifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("NotifiedTo")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("NotificationId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("RapidFireLib.Models.Payment.ConfigBKashAuth", b =>
                {
                    b.Property<string>("PId")
                        .HasColumnType("text");

                    b.Property<string>("AppKey")
                        .HasColumnType("text");

                    b.Property<string>("AppSecret")
                        .HasColumnType("text");

                    b.Property<string>("CheckoutURL")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("PId");

                    b.ToTable("ConfigBKashAuth");
                });

            modelBuilder.Entity("RapidFireLib.Models.QuickSearch", b =>
                {
                    b.Property<int>("SearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SearchId"));

                    b.Property<string>("GroupTitle")
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("SearchUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("SearchId");

                    b.ToTable("QuickSearch");
                });

            modelBuilder.Entity("RapidFireLib.Models.RoleType", b =>
                {
                    b.Property<int>("RoleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleTypeId"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("RoleTypeId");

                    b.ToTable("RoleType");
                });

            modelBuilder.Entity("RapidFireLib.Models.Schedular", b =>
                {
                    b.Property<string>("SchedularId")
                        .HasColumnType("text");

                    b.Property<string>("CexSL")
                        .HasColumnType("text");

                    b.Property<string>("CornEx")
                        .HasColumnType("text");

                    b.Property<string>("DayOfMonth")
                        .HasColumnType("text");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("text");

                    b.Property<string>("Hours")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JobName")
                        .HasColumnType("text");

                    b.Property<string>("Minutes")
                        .HasColumnType("text");

                    b.Property<string>("Months")
                        .HasColumnType("text");

                    b.Property<string>("NthDayOfWeek")
                        .HasColumnType("text");

                    b.Property<string>("Seconds")
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .HasColumnType("text");

                    b.HasKey("SchedularId");

                    b.ToTable("Schedular");
                });

            modelBuilder.Entity("RapidFireLib.Models.UserGlobalGeo", b =>
                {
                    b.Property<int>("UserGlobalGeoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserGlobalGeoId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<int>("FieldOfficeId")
                        .HasColumnType("integer");

                    b.Property<int>("ProgramId")
                        .HasColumnType("integer");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("UserGlobalGeoId");

                    b.ToTable("UserGlobalGeo");
                });

            modelBuilder.Entity("RapidFireLib.Models.UserRoleGeo", b =>
                {
                    b.Property<int>("UserRoleGeoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserRoleGeoId"));

                    b.Property<string>("DistrictCode")
                        .HasColumnType("text");

                    b.Property<string>("DivisionCode")
                        .HasColumnType("text");

                    b.Property<string>("UnionCode")
                        .HasColumnType("text");

                    b.Property<string>("UpazilaCode")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("VillageCode")
                        .HasColumnType("text");

                    b.HasKey("UserRoleGeoId");

                    b.ToTable("UserRoleGeo");
                });

            modelBuilder.Entity("RapidFireLib.Models.UserSLGeo", b =>
                {
                    b.Property<int>("UserSLGeoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserSLGeoId"));

                    b.Property<int>("ChildrenClubCode")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyCode")
                        .HasColumnType("integer");

                    b.Property<int>("EstateDivisionCode")
                        .HasColumnType("integer");

                    b.Property<int>("TeaEstateCode")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("UserSLGeoId");

                    b.ToTable("UserSLGeo");
                });

            modelBuilder.Entity("RapidFireLib.View.Models.AppResource", b =>
                {
                    b.Property<int>("AppResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppResourceId"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool?>("HasLeftMenu")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasSeparator")
                        .HasColumnType("boolean");

                    b.Property<string>("IconClass")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsModel")
                        .HasColumnType("boolean");

                    b.Property<bool?>("MenuIsVisible")
                        .HasColumnType("boolean");

                    b.Property<int?>("MenuOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("AppResourceId");

                    b.ToTable("AppResources");
                });

            modelBuilder.Entity("RapidFireLib.View.Models.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAllFieldOffice")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAllProgram")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.Property<int>("RoleIndex")
                        .HasColumnType("integer");

                    b.Property<int>("RoleType")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("RapidFireLib.View.Models.Identity.ApplicationUserLogin", b =>
                {
                    b.Property<int>("IdentityUserLoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdentityUserLoginId"));

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("IdentityUserLoginId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("RapidFireLib.View.Models.Identity.AspNetUsers", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("CreateBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EditBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FBEmail")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("GoogleEmail")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MSEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<string>("ResetPasswordCode")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TWEmail")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("RapidFireLib.View.Models.ModelDefaults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FieldName")
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<int>("OptionOrder")
                        .HasColumnType("integer");

                    b.Property<string>("OptionText")
                        .HasColumnType("text");

                    b.Property<string>("OptionValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ModelDefaults");
                });

            modelBuilder.Entity("RapidFireLib.View.Models.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TenantId"));

                    b.Property<string>("ContactAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Host")
                        .HasColumnType("text");

                    b.Property<bool>("IsPendingUpdate")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubdomainName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TenantType")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("TenantId");

                    b.ToTable("Tenant");
                });

            modelBuilder.Entity("RapidFireLib.View.Models.UserDesignation", b =>
                {
                    b.Property<int>("DesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DesignationId"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("DesignationId");

                    b.ToTable("UserDesignations");
                });

            modelBuilder.Entity("RapidFireLib.Models.ChatGroupMember", b =>
                {
                    b.HasOne("RapidFireLib.Models.ChatGroup", null)
                        .WithMany("ChatGroupMember")
                        .HasForeignKey("ChatGroupId");
                });

            modelBuilder.Entity("RapidFireLib.Models.ChatSeenUser", b =>
                {
                    b.HasOne("RapidFireLib.Models.ChatMessage", null)
                        .WithMany("ChatSeenUser")
                        .HasForeignKey("ChatMessageId");
                });

            modelBuilder.Entity("RapidFireLib.Models.FCMCUDTopic", b =>
                {
                    b.HasOne("RapidFireLib.Models.FCMCUDSetup", null)
                        .WithMany("FCMCUDTopic")
                        .HasForeignKey("FCMCUDSetupId");
                });

            modelBuilder.Entity("RapidFireLib.Models.ChatGroup", b =>
                {
                    b.Navigation("ChatGroupMember");
                });

            modelBuilder.Entity("RapidFireLib.Models.ChatMessage", b =>
                {
                    b.Navigation("ChatSeenUser");
                });

            modelBuilder.Entity("RapidFireLib.Models.FCMCUDSetup", b =>
                {
                    b.Navigation("FCMCUDTopic");
                });
#pragma warning restore 612, 618
        }
    }
}
